### ISSUE TITLE
i can't find model of fewshot

### ISSUE THREAD

**Issue by sorryandbyebye** [ahirsharan/MTL_Segmentation#1]
Hello, can you provide the pre-training model of FEwSHOT?

**Comment by ahirsharan** [comment]
Here: https://drive.google.com/drive/folders/1XINoAV2riFToAAs4NzGscB6vbKCkVdAo?usp=sharing

**Comment by sorryandbyebye** [comment]
Do you mean that coco and fewshot use the same pre-training model?

**Comment by ahirsharan** [comment]
Only coco is used for pre-training. Few-Shot is for the meta phase.

**Comment by sorryandbyebye** [comment]
thank you~
